### PR TITLE
Try again to fix migrations

### PR DESCRIPTION
**Pull request by MatthewPiatetsky**
@edx/ecommerce 
Is there a way I can deploy a branch to stage catalog to test if my migration fix worked?
I think the issue with my previous PR was that I reverted my migration changed but didn't rename the file back.

### CODE REVIEW

**Comment by schenedx** [comment]
@MatthewPiatetsky I think you should investigate whether we can setup discovery service in a sandbox. See https://openedx.atlassian.net/wiki/display/EdxOps/Sandboxes.

**Review by schenedx — APPROVED** [review]
👍  But what's with travis build on this PR?

**Comment by MatthewPiatetsky** [comment]
@schenedx all my travis builds were failing due to timeouts with github
This time around the log message is unclear, but think it is related to that.
I had to restart the build like 5 times on my previous PR to get it to pass.

**Comment by cpennington** [comment]
@MatthewPiatetsky @schenedx: What was it about your dev environments that made it so you couldn't reproduce this issue locally (and had to rely on stage/a sandbox)?

**Pull request merged**
