### PR TITLE
feat: Replace dry-rest-permissions with Django 3.2 compatible fork

### PR DESCRIPTION
**Pull request by giovannicimolin**
This PR replaces [dry-rest-permissions](https://github.com/Helioscene/dry-rest-permissions) with a fork that has support and tests passing for Django 3.2 (https://github.com/FJNR-inc/dry-rest-permissions).

This should be a drop-in replacement, so no issues are expected.

Solves https://github.com/edx/upgrades/issues/58

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-6466](https://openedx.atlassian.net/browse/OSPR-6466) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by giovannicimolin** [comment]
@natabene This is ready for review.

**Comment by natabene** [comment]
New JIRA link: https://openedx.atlassian.net/browse/OSPR-6474

**Comment by zainab-amir** [comment]
@giovannicimolin can you kindly rebase your branch?

**Review by zainab-amir — APPROVED** [review]

**Comment by giovannicimolin** [comment]
@zainab-amir Rebased! :)

**Comment by openedx-webhooks** [comment]
@giovannicimolin 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3297&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2022-02-16+18:44&entry.1917517419=2022-03-24+06:22&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
