### PR TITLE
Update active courses to exclude runs whose end date has passed

### PR DESCRIPTION
**Pull request by bderusha**
[ECOM-4480](https://openedx.atlassian.net/browse/ECOM-4480)

@clintonb @peter-fogg Please review

### CODE REVIEW

**Comment by clintonb** [comment]
What about self-paced courses? Do they have end dates?

**Comment by bderusha** [comment]
@clintonb they do

**Comment by clintonb** [comment]
👍

**Comment by peter-fogg** [comment]
👍

**Pull request merged**
