### PR TITLE
BOM-1400 : Create Django 2.x Travis workers

### PR DESCRIPTION
**Pull request by mzulqarnain1**
Relevant JIRA : [https://openedx.atlassian.net/browse/BOM-1400](https://openedx.atlassian.net/browse/BOM-1400)

### CODE REVIEW

**Comment by mzulqarnain1** [comment]
Hey @jmbowman Currently builds are failing in course-discovery in due to some firefox installation issue 
```
Errors were encountered while processing:
 firefox
The command "docker exec -t discovery bash -c 'sudo dpkg -r --force-all firefox && TEMP_DEB="$(mktemp)" && wget -O "$TEMP_DEB" https://s3.amazonaws.com/vagrant.testeng.edx.org/firefox_61.0.1%2Bbuild1-0ubuntu0.16.04.1_amd64.deb && dpkg -i "$TEMP_DEB"'" failed and exited with 1 during .
```
Can you look into it a little?

**Comment by jmbowman** [comment]
```
 firefox depends on libstartup-notification0 (>= 0.8); however:

  Package libstartup-notification0 is not installed.
```

It looks like we've been installing the latest firefox from Ubuntu and then downgrading to a specific version we have in an S3 bucket, but the Ubuntu firefox was just upgraded to a version that no longer requires one of the dependencies needed for that older version.  We'll have to update our setup to explicitly install that one (and any others that may no longer be needed by the newer firefox version.)

master build yesterday with the same issue: https://travis-ci.org/github/edx/course-discovery/jobs/661346473
master build from earlier yesterday that worked and lists the packages needed by the previous firefox release: https://travis-ci.org/github/edx/course-discovery/jobs/661057692

**Comment by jmyatt** [comment]
PR #2471 should fix this

**Comment by mzulqarnain1** [comment]
Hi @jmbowman, I have done most of the work required for this task. but the builds seems to be failing, most of the tests fail even on django111 environment without telling any reason, we only get one error `Fatal Python error: Segmentation fault` , Do you have any idea about it?

**Comment by jmbowman** [comment]
I tried running the first failure locally and was able to reproduce it:

```
_______ TestStdImageSerializerField.test_to_representation _______

self = <course_discovery.apps.api.tests.test_fields.TestStdImageSerializerField object at 0x7f83e028ae48>

    def test_to_representation(self):
        request = make_request()
        program = ProgramFactory(banner_image=make_image_file('test.jpg'))
        field = StdImageSerializerField()
        field._context = {'request': request}  # pylint: disable=protected-access
        expected = {
            size_key: {
                'url': '{}{}'.format('http://testserver', getattr(program.banner_image, size_key).url),
                'width': program.banner_image.field.variations[size_key]['width'],  # pylint: disable=no-member
                'height': program.banner_image.field.variations[size_key]['height']  # pylint: disable=no-member
            } for size_key in program.banner_image.field.variations}  # pylint: disable=no-member
>       assert field.to_representation(program.banner_image) == expected
E       AssertionError: assert {'large': {'h...'width': 348}} == {'large': {'h...'width': 348}}
E         Differing items:
E         {'x-small': {'height': 116, 'url': 'http://localhost:18381/media/media/programs/banner_images/c14e0adb-f2b1-4880-a55b-d58f435ba9b7-db4d1a82ff02.x-small.jpg', 'width': 348}} != {'x-small': {'height': 116, 'url': 'http://testserverhttp://localhost:18381/media/media/programs/banner_images/c14e0adb-f2b1-4880-a55b-d58f435ba9b7-db4d1a82ff02.x-small.jpg', 'width': 348}}
E         {'small': {'height': 145, 'url': 'http://localhost:18381/media/media/programs/banner_images/c14e0adb-f2b1-4880-a55b-d58f435ba9b7-db4d1a82ff02.small.jpg', 'width': 435}} != {'small': {'height': 14...
E         
E         ...Full output truncated (4 lines hidden), use '-vv' to show

course_discovery/apps/api/tests/test_fields.py:32: AssertionError
```

Note: `http://testserverhttp://localhost:18381/media/...`

I'm guessing many of the errors are due to environment variables blocked by tox.  Have you tried running just one test class at a time locally via tox?  Probably easier to debug there than figure out what's happening on Travis.

**Comment by mzulqarnain1** [comment]
@jmbowman I have run the tests individually which were failing and they run just fine. the problem occurs when tests are run collectively. Then the  `SegmentationFault` occurs. and It doesn't occur in the same file always ( Soban ran the tests and it gave SegFault in different files ) which is further proof that this is not specific to any test. I am looking into this problem but so far unable to find any cause.

**Comment by mzulqarnain1** [comment]
@jmbowman One thing to note is that when I run tests locally with [settings/test_local.py](https://github.com/edx/course-discovery/blob/master/course_discovery/settings/test_local.py) the tests run just fine.

**Comment by jmbowman** [comment]
Yes, it's probably a problem with something like environment variables or hash seed randomization under tox.  There's a ticket for someone in the Cambridge office to help look into this.

**Comment by mzulqarnain1** [comment]
Continued in [https://github.com/edx/course-discovery/pull/2508](https://github.com/edx/course-discovery/pull/2508) , Closing this one.

**Pull request closed without merging**
