### PR TITLE
Adding tabular inline data in admin for a course with course-runs and…

### PR DESCRIPTION
**Pull request by awais786**
Adding inline items on admin course detail page.

- Course Runs
- Course UserRoles

https://openedx.atlassian.net/browse/EDUCATOR-739

### CODE REVIEW

**Comment by awais786** [comment]
screen shot 2017-06-24 at 3 20 33 pm

**Comment by awais786** [comment]
@asadazam93 Please review this.

**Review by Ayub-Khan — APPROVED** [review]
Looks good to me.

**Review by clintonb — CHANGES_REQUESTED** [review]
What are you trying to accomplish here? Your ticket has zero details. Any Django admin component using the user model is a bad idea. That's a good way to bring down the database.

**Comment by awais786** [comment]
@clintonb but I am using the raw-id for user and also exclude the changed-by.

**Comment by awais786** [comment]
I m closing this PR for time being.

**Comment by clintonb** [comment]
The moment someone clicks the search icon, a window will open that loads the entire user table. That will cause an issue with the database.

**Pull request closed without merging**
