### PR TITLE
build: add python311 and python312 CI support

### LINKED ISSUE #4307: [course-discovery] Test Python 3.11 and 3.12
We should ideally aim for python 3.12 but if there are major issues, we should fall back to 3.11

### PR DESCRIPTION
**Pull request by ichintanjoshi**
## Description 

This PR contains changes for upgrading python 3.8 to python 3.11 & 3.12

Changes include :-
- Dependencies and version upgrades

Done as a part of following :-
- https://github.com/openedx/public-engineering/issues/233
- https://github.com/openedx/edx-platform/issues/34229
- https://github.com/openedx/course-discovery/issues/4307

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ichintanjoshi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @openedx/course-discovery-maintainers! Would someone be able to review this for us? Thanks!

**Review by zawan-ila — APPROVED** [review]

**Review by DawoudSheraz — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ichintanjoshi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/4320&entry.1484655318=https://github.com/ichintanjoshi&entry.752974735=2024-04-08+13:28&entry.1917517419=2024-04-15+06:12&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by iamsobanjaved** [comment]
This PR didn't run unit tests on python 3.11 and 3.12 versions because these versions weren't available on the docker image and the test suites just skipped unit tests. For the services that run CI on docker, we need to modify Dockerfile as well.

> py311-django42: skipped because could not find python interpreter with spec(s): py311

https://github.com/openedx/course-discovery/actions/runs/8684080396/job/23811059094#step:4:1646 

>py312-django42: skipped because could not find python interpreter with spec(s): py312

https://github.com/openedx/course-discovery/actions/runs/8684080396/job/23811059586#step:4:1646

**Comment by feanil** [comment]
@iamsobanjaved or @ichintanjoshi is one of you working on fixing this?

**Comment by iamsobanjaved** [comment]
Yup @feanil, almost ready, just need to clean commits, will do shortly.

Fix: https://github.com/openedx/course-discovery/pull/4328

**Comment by ichintanjoshi** [comment]
@feanil I am coming back from vacation on Monday and will take a look into it.

**Comment by iamsobanjaved** [comment]
#4328 is ready for review, it updates the Dockerfile to add support for Python 3.11 and 3.12

cc @feanil @ichintanjoshi

**Pull request merged**
