### PR TITLE
refactoring: get rid of outdated django-taggit-serializer package

### LINKED ISSUE #18: Update or replace django-taggit-serializer
We use the package [django-taggit-serializer](https://github.com/glemmaPaul/django-taggit-serializer) in edx/course-discovery. This package was last released in 2018 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

### PR DESCRIPTION
**Pull request by regisb**
The django-taggit-serializer library has been vendored in django-taggit,
now hosted by jazzband:
https://github.com/jazzband/help/issues/91#issuecomment-871498498

Thus, we can get rid of this package and simply change the import paths.
This is necessary for Django 3.2 compatibility.

Close https://github.com/edx/upgrades/issues/18

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @regisb! I've created [OSPR-6034](https://openedx.atlassian.net/browse/OSPR-6034) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by regisb** [comment]
This is ready for review @natabene.

**Comment by natabene** [comment]
@regisb Thank you for your contribution!

**Comment by natabene** [comment]
@wajeeha-khalid This PR is in support of our Django upgrade project. Could your team please review it next week?

**Review by uzairr — APPROVED** [review]
Looks good to me, approving this PR on behalf of discovery owning squad! 👍

**Comment by wajeeha-khalid** [comment]
> @wajeeha-khalid This PR is in support of our Django upgrade project. Could your team please review it next week?

@natabene for sure; this Pr is also part of https://openedx.atlassian.net/browse/VAN-705 and team has already picked this up.

**Comment by openedx-webhooks** [comment]
@regisb 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/3122&entry.1484655318=https://github.com/regisb&entry.752974735=2021-09-09+20:52&entry.1917517419=2021-09-14+06:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
