### PR TITLE
Added changed_by field in all publisher models and decorated all views with login_required.

### PR DESCRIPTION
**Pull request by waheedahmed**
[ECOM-5469](https://openedx.atlassian.net/browse/ECOM-5469)

**Acceptance Criteria:**
1. Decorate all publisher views with login_required.
2. Add changed-by ( user foreign key ) in all publisher models.
3. While create/update course , runs and seats and changing state save the user in db as changed_by.

### CODE REVIEW

**Comment by waheedahmed** [comment]
@awais786 Please review.

**Comment by waheedahmed** [comment]
@bderusha Please review.

**Comment by bderusha** [comment]
👍

**Comment by awais786** [comment]
👍

**Pull request merged**
