### PR TITLE
Wrap ES search query in parens to perserve semantics

### PR DESCRIPTION
**Pull request by mjfrey**
Add parens around query so the addition of the partner filter does not change the query semantics.

### CODE REVIEW

**Comment by mjfrey** [comment]
@clintonb @mattdrayer Please review

**Comment by clintonb** [comment]
@mjfrey did you figure out why this is necessary? Until we have an explanation for why this is broken, we should not merge a fix that may cause other issues.

**Comment by mjfrey** [comment]
@clintonb yes this is necessary by looking at the ES logs.  The filter adds "AND partner:xxx" to the query thus changing the semantics.  By adding the parens, we preserve the original query.

**Comment by clintonb** [comment]
@mjfrey did you dig deeper? _Why_ is the initial query modified by adding the `filter` clause?

**Comment by mjfrey** [comment]
@clintonb adding a filter to a SearchQuerySet just adds the clause "AND ...." thus changing it.

**Comment by mjfrey** [comment]
I should clarify.  The original query is not modified.  Just its meaning by adding an AND at the end of it does.

**Comment by mattdrayer** [comment]
👍

**Comment by clintonb** [comment]
@mjfrey please update your comment to reflect this.

**Comment by mjfrey** [comment]
@clintonb how's that look?

**Comment by clintonb** [comment]
@mjfrey comment looks good, but this change belongs in `course_metadata.utils.clean_query`. That way all of our search code can take advantage of it.

**Comment by mjfrey** [comment]
@mattdrayer @clintonb I moved wrapping the query to utils.py

**Comment by clintonb** [comment]
👍

**Pull request merged**
