### PR TITLE
Add missing migration files for Mode and Program

### PR DESCRIPTION
**Pull request by kdmccormick**

### CODE REVIEW

**Review by Dillon-Dumesnil — APPROVED** [review]
The certificate_type change was a miss on my pat. Forgot that choices updates are a model change. I can vouch for the Mode model changes.

**Comment by Dillon-Dumesnil** [comment]
Also, call it a nit, but I'd prefer if we can change the file name to something more descriptive of the changes instead of just "missing" migrations. They are missing to us, not to the community at large.

**Comment by kdmccormick** [comment]
@Dillon-Dumesnil I'm all for descriptive migration names. Best I can think of is `0259_deprecate_program_card_image_url_and_add_exec_ed_mode.py` -- lmk if you have a better idea :stuck_out_tongue:

**Comment by kdmccormick** [comment]
Went with `0259_depr_program_card_image_url_and_add_exec_ed_cert_type.py`

**Comment by Dillon-Dumesnil** [comment]
Love it! Thank you :)

**Pull request merged**
