### PR TITLE
refactor: ignore non-english transcripts in xblock provider

### PR DESCRIPTION
**Pull request by navinkarkera**
The current implementation of skill tagging in taxonomy_connector only supports english text via lightcast api. This commit ignores all other transcripts while collecting the text representation of any video xblock.

## Testing instructions

- Checkout https://github.com/openedx/edx-platform/pull/32099, this is required due a bug in multiple transcripts uploader.
- Start `lms` and `discovery` service in devstack using `make lms-up discovery-up`
- Follow instructions in https://github.com/openedx/edx-platform/pull/32099 to add multiple transcripts to any video xblock.
- Check whether the api returns multiple transcripts for the video using below url:
```
# change the block key to the video xblock usage key that you are testing.
http://localhost:18000/api/courses/v2/block_metadata/block-v1:edX+DemoX+Demo_Course+type@video+block@7e3e72fda7054aeeb7fd343f93ebb520?include=index_dictionary
```
- Follow [instructions given here](https://github.com/openedx/taxonomy-connector#getting-started) to setup taxonomy-connector in course-discovery, make sure to clone `https://github.com/open-craft/taxonomy-connector` in `<devstack-base-dir>/src/`
- Open discovery shell using `make discovery-shell`
- Run `./manage.py migrate`
- Open django shell using `./manage.py shell`
- Run below commands to make
```python
from course_discovery.apps.taxonomy_support.providers import DiscoveryXBlockMetadataProvider
provider = DiscoveryXBlockMetadataProvider()
blocks = provider.get_xblocks(["<use_the_same_video_xblock_usage_key"])
print(blocks) # should only contain the english transcript in content.
```

**Dependencies:** https://github.com/openedx/edx-platform/pull/32099

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @navinkarkera!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by Cup0fCoffee** [comment]
:+1:

- [x] I tested this: followed the testing instructions
- [x] I read through the code

@navinkarkera Can you please specify https://github.com/openedx/edx-platform/pull/32099 as a dependency in the PR description?

**Comment by navinkarkera** [comment]
@sameenfatima78 This is ready for your review.

**Review by sameenfatima78 — APPROVED** [review]

**Comment by mphilbrick211** [comment]
Hi @navinkarkera! Now that the dependent PR is merged, is this ready for review/merge?

**Comment by sameenfatima78** [comment]
@mphilbrick211 I'll take care of tagging the appropriate person who can review and merge it. 
@navinkarkera Meanwhile, can you rebase the branch to master?

**Review by DawoudSheraz — COMMENTED** [review]
Missing unit tests.

**Comment by navinkarkera** [comment]
@DawoudSheraz Although we have validators which validates basic functionality of these providers, it was not testing the specific functionality added in this PR. Added a single test specifically for this case.
cc: @sameenfatima78

**Review by DawoudSheraz — APPROVED** [review]

**Comment by sameenfatima78** [comment]
@DawoudSheraz If all looks okay, can you please merge it?

**Comment by navinkarkera** [comment]
@DawoudSheraz Gentle reminder to merge this PR.

cc: @sameenfatima78

**Comment by DawoudSheraz** [comment]
> @DawoudSheraz Gentle reminder to merge this PR.
> 
> cc: @sameenfatima78

Please rebase the branch. Thanks.

**Comment by navinkarkera** [comment]
> > @DawoudSheraz Gentle reminder to merge this PR.
> > cc: @sameenfatima78
> 
> Please rebase the branch. Thanks.

@DawoudSheraz Done.

**Comment by openedx-webhooks** [comment]
@navinkarkera 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3900&entry.1484655318=https://github.com/navinkarkera&entry.752974735=2023-04-19+15:05&entry.1917517419=2023-07-06+07:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
