### PR TITLE
Changed requirements to pull edx-i18n-tools from PyPI and .gitignore …

### PR DESCRIPTION
**Pull request by Dillon-Dumesnil**
…to include en files

@clintonb @bderusha Please review

### CODE REVIEW

**Comment by iivic** [comment]
@clintonb  @mjfrey  Please review.

**Comment by clintonb** [comment]
Rebase and commit the English .po files.

**Comment by iivic** [comment]
English .po files added. Review once more.

**Comment by iivic** [comment]
Please confirm merge.

**Comment by clintonb** [comment]
👍

**Pull request merged**
