### PR TITLE
ECOM-5387

### PR DESCRIPTION
**Pull request by awais786**
Minor changes in programs-page.
https://openedx.atlassian.net/browse/ECOM-5387

### CODE REVIEW

**Comment by awais786** [comment]
Course Runs look fixed.
screen shot 2016-08-27 at 8 21 17 pm

**Comment by awais786** [comment]
Back button also added.
screen shot 2016-08-27 at 8 22 41 pm

**Comment by awais786** [comment]
@bderusha Please review.

**Comment by bderusha** [comment]
👍

**Comment by waheedahmed** [comment]
👍

**Pull request merged**
