### PR TITLE
WS-1292 Explicitly allow prospectus worker to get all orgs

### PR DESCRIPTION
**Pull request by rgraber**

### CODE REVIEW

**Review by mikix — APPROVED** [review]
Presumably we'll drop this once we fix the user up again.

**Comment by rgraber** [comment]
> Presumably we'll drop this once we fix the user up again.

that's the plan. SRE is aware of the issue.

**Review by albemarle — APPROVED** [review]
Can you add the Jira ticket to the commit message?

**Comment by rgraber** [comment]
> Can you add the Jira ticket to the commit message?

Will do

**Pull request merged**
