### PR TITLE
Default to ordering Person by id, because that has an index, unlike c…

### PR DESCRIPTION
**Pull request by cpennington**
…reated

### CODE REVIEW

**Review by xnick421 — COMMENTED** [review]
Is the migration supposed to be part of this pr?

**Comment by cpennington** [comment]
There's a few changes from before whose migrations got missed. This change does require a migration as well. I could split them up, though

**Review by Dillon-Dumesnil — APPROVED** [review]
Looks good. Jeff and Becca talked about the other parts of the migration already, so those are fine to keep as well. I know Stuart Young has a PR that was also picking these other migrations up so maybe just talk to him to avoid any conflicts (I'm not sure if anything breaks if you have the same operation in two separate migrations).

**Comment by Dillon-Dumesnil** [comment]
Doesn't look like Stu has an open PR so it might be good to just shoot him a message that he doesn't need to worry about those after a rebase and you're good to merge.

**Pull request merged**
