### PR TITLE
Script to fix orgs

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
@schenedx this script should do what we want. I'll let you take over from here, if you're in the office tomorrow.

FYI @edx/devops we'll want to run this in a Django shell after review

**Comment by schenedx** [comment]
@clintonb Can you please review my edits?

**Comment by clintonb** [comment]
@schenedx your changes look good to me.

**Comment by clintonb** [comment]
👍

**Pull request closed without merging**
