### PR TITLE
i18n Cleanup

### PR DESCRIPTION
**Pull request by clintonb**
Line numbers in PO files are noisy in pull requests. This commit updates the Makefile to use edx-i18n-tools to extract translations and remove line numbers.

Additionally, a few uses of `blocktrans` have been updated to use the `trimmed` argument to remove surrounding whitespace.

ECOM-5175

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/ecommerce

**Comment by clintonb** [comment]
@waheedahmed this will help reduce the line count in #382.

**Comment by MatthewPiatetsky** [comment]
@clintonb forget if I asked this before, is there documentation somewhere on how the whole translations system works in course_discovery
There is this https://open-edx-course-catalog.readthedocs.io/en/latest/internationalization.html, but it doesn't seem to have many details on course_discovery specifically rather than transifex

**Comment by clintonb** [comment]
@MatthewPiatetsky all of our IDAs behave the same, so the documentation is pretty standard. The changes regarding validation are pretty new, and documentation has not been updated.

**Pull request merged**
