### PR TITLE
[SE-3515] Handle JSON decoder error is api returns 404

### PR DESCRIPTION
**Pull request by pkulkark**
This small PR handles the JSON decoder error that is seen if the program api returns 404 when running `refresh_course_metadata` command. It checks the status code of the response before calling the json() method.

**Jira Tickets:** [OSPR-5078](https://openedx.atlassian.net/browse/OSPR-5078)

**Testing Instructions:**
1. Ensure no programs are indexed. Running the command `/edx/bin/manage.discovery update_index --disable-change-limit` should show 0 programs.
2. Run command `/edx/bin/manage.discovery refresh_course_metadata`.
3. Verify command succeeds without any errors.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pkulkark! I've created [OSPR-5078](https://openedx.atlassian.net/browse/OSPR-5078) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@pkulkark Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by samuelallan72** [comment]
@pkulkark :+1:

- [x] I tested this: followed test instructions
- [x] I read through the code
- [ ] NA I checked for accessibility issues
- [x] Includes documentation

**Comment by pkulkark** [comment]
@natabene This is good for edX's review

**Comment by natabene** [comment]
@pkulkark Thanks for letting me know. @emma-green Is this something your team can review?

**Comment by Dillon-Dumesnil** [comment]
Hi @natabene , Course-Discovery Pull Requests will be reviewed by the `edx/course-discovery-admins` group. We have already been tagged on this PR and will try and review it soon.

Sorry for the ping Emma!

**Comment by Dillon-Dumesnil** [comment]
Hi @pkulkark , I'm curious as to how you were running into the scenario of getting a 404. I ran some tests locally where if I hit `http://localhost:18381/api/v1/programs/?page=1&page_size=50` with 0 Programs, I would get a response with empty results (as opposed to a 404).
```
{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```
However, if I hit with a later page, (i.e. `http://localhost:18381/api/v1/programs/?page=2&page_size=50`), I would get a 404 with the response of 
```
{
    "detail": "Invalid page."
}
```
However, when running the data loader, a later page should never be hit unless the previous page returned a value for `"next"`. Some insight into how you are hitting this problem would be very helpful.

When running Refresh Course Metadata with the partner programs API url of `http://localhost:18381/api/v1/`, I receive the following output from the management command 
```
2020-10-28 16:02:34,091 INFO 15203 [course_discovery.apps.course_metadata.management.commands.refresh_course_metadata] /edx/app/discovery/discovery/course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py:164 - Executing Loader [http://edx.devstack.discovery:18381/api/v1/]
2020-10-28 16:02:34,104 INFO 15203 [course_discovery.apps.course_metadata.data_loaders.api] /edx/app/discovery/discovery/course_discovery/apps/course_metadata/data_loaders/api.py:791 - Refreshing programs from http://edx.devstack.discovery:18381/api/v1/...
2020-10-28 16:02:34,734 INFO 15203 [course_discovery.apps.course_metadata.data_loaders.api] /edx/app/discovery/discovery/course_discovery/apps/course_metadata/data_loaders/api.py:798 - Retrieved 0 programs...
2020-10-28 16:02:34,734 INFO 15203 [course_discovery.apps.course_metadata.data_loaders.api] /edx/app/discovery/discovery/course_discovery/apps/course_metadata/data_loaders/api.py:809 - Retrieved 0 programs from http://edx.devstack.discovery:18381/api/v1/
```
which is what I would expect would be happening.

**Comment by pkulkark** [comment]
@Dillon-Dumesnil Thanks for the details. We ran into this issue on one of our clients' instance that is running on `juniper.3` branch. I'm not really sure why we didn't see the expected behaviour. We didn't change any config apart from the API url using the external domain name instead of `localhost`. Whenever we ran the `refresh_course_metadata` management command, it failed with a JSONDecodeError at the line changed in this PR. Perhaps it required some additional config that we missed? In any case, the change only affects if the response status is other than 200.

**Comment by Dillon-Dumesnil** [comment]
@pkulkark , Ah okay, thank you for the additional information! So I don't think there is any issue in making the Refresh Course Metadata command more defensive, but I would request that we change the logic from `response.status_code != 200` to `response.raise_for_status()`. We don't want the job to simply swallow any potential errors by just returning. This will cause the job to continue to fail for your client however, so I'm not sure if that is a solution you want. 

I would recommend trying to dig deeper into what is happening with your client's instance. Like perhaps trying to directly hitting the endpoint it is failing on and seeing what the message displayed is? I don't _think_ there is any additional config that might be missing.

**Comment by natabene** [comment]
@pkulkark Just checking to see if you had to address our feedback.

**Comment by pkulkark** [comment]
@Dillon-Dumesnil Yup that makes sense. I've changed it to `response.raise_for_status()`.

**Comment by Dillon-Dumesnil** [comment]
Thank you @pkulkark ! I would like to request that this change is also made into the Koa branch and the master branch of this repo and was hoping you might be able to put up those PRs and tag me on them for approval. Without merging these changes into those branches, the Koa release and all future releases will not have this change. Should hopefully be an easy thing to do since you already have this branch! Please let me know if that is something you can do.

**Comment by pkulkark** [comment]
@Dillon-Dumesnil Thanks, I've created #2889 for `master` branch and #2891 for `koa` branch and tagged you in both. Please let me know if I missed anything.

**Review by Dillon-Dumesnil — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@pkulkark 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/2793&entry.1484655318=https://github.com/pkulkark&entry.752974735=2020-10-22+13:20&entry.1917517419=2021-01-15+11:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by Dillon-Dumesnil** [comment]
All looks great to me! Thank you @pkulkark for making these changes!

**Pull request merged**
