### PR TITLE
test cases for whitelabel journal

### PR DESCRIPTION
**Pull request by ibrahimahmed443**

### CODE REVIEW

**Comment by ibrahimahmed443** [comment]
@bill-filler Work in progress.

**Comment by bill-filler** [comment]
@ibrahimahmed443 
are we supposed to be committing .po files? I thought they got generated automatically?

**Comment by ibrahimahmed443** [comment]
@bill-filler Yes, we need those here, otherwise the tests won't pass. These files exist in other parts of the code as well.

**Comment by bill-filler** [comment]
Go ahead and merge please. Nice work!

**Review by bill-filler — APPROVED** [review]
Approved

**Pull request merged**
