### PR TITLE
Removed the Program.category field

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/ecommerce please review

**Comment by schenedx** [comment]
@clintonb Do we also need to remove `catalog` from https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/serializers.py#L52? If not, how does that field gets populated in search results?

**Comment by clintonb** [comment]
Updated. Thanks, @schenedx.

**Comment by schenedx** [comment]
👍

**Comment by rlucioni** [comment]
👍

**Pull request merged**
