### PR TITLE
chore: update django-autocomplete-light

### PR DESCRIPTION
**Pull request by cmltaWt0**
Changes:
- update django-autocomplete-light version to RC [3.9.0rc1](https://pypi.org/project/django-autocomplete-light/3.9.0rc1/)
- 3.9.0rc1 is compatible with both Django3.2 and Django2.2.24

Important fix in the RC: https://github.com/yourlabs/django-autocomplete-light/commit/3397ad5424d621021efb0af67be08ff46e7d4533

I'm proposing to consider using RC version and upgrade as soon as release version will be uploaded to PYPI.

I've tested this version with both Django2.2.4 and Django3.2.
Checked all admin forms. Hopefully didn't miss anything.

---
Issues still in master but not released in a new RC or a release version:
- https://github.com/yourlabs/django-autocomplete-light/commit/561c9cc56aa94aed88e54e85127ec6d65021667f
- https://github.com/yourlabs/django-autocomplete-light/commit/23a8052295553258fdfefd3d06bd8d48a4168c39
- https://github.com/yourlabs/django-autocomplete-light/commit/925bed816586a41bf5f959eb5b041e84b49d94eb

---
Edx upgrades task: https://github.com/edx/upgrades/issues/20

---
There are some screenshots (not all cases).
Screenshot 2021-09-30 at 19 48 15
Screenshot 2021-09-30 at 19 45 32
Screenshot 2021-09-30 at 19 45 01
Screenshot 2021-09-30 at 19 44 27

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @cmltaWt0! I've created [OSPR-6087](https://openedx.atlassian.net/browse/OSPR-6087) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@cmltaWt0 Thank you for your contribution. Is this ready for our review?

**Comment by cmltaWt0** [comment]
> @cmltaWt0 Thank you for your contribution. Is this ready for our review?

Yes. It's ready.

**Comment by awais786** [comment]
@cmltaWt0 I will review this. I will try to test this locally or on sandbox.

**Review by awais786 — APPROVED** [review]

**Comment by awais786** [comment]
@waheedahmed Please check this PR. It seems fine I have tested also.

**Review by uzairr — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@cmltaWt0 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/3163&entry.1484655318=https://github.com/cmltaWt0&entry.752974735=2021-09-30+17:12&entry.1917517419=2021-10-04+14:06&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
