### PR TITLE
Awais786/fixing django2 migrations

### PR DESCRIPTION
**Pull request by Ayub-Khan**
Testing django2.2 tests 

its just for experiments.

### CODE REVIEW

**Comment by Dillon-Dumesnil** [comment]
I just want to call out the similarities between this PR and #2483 so you two (Awais and Ayub) can avoid merge conflicts. Once it is resolved over who will be merging in the changes, I can review either or both PRs.

**Comment by awais786** [comment]
> I just want to call out the similarities between this PR and #2483 so you two (Awais and Ayub) can avoid merge conflicts. Once it is resolved over who will be merging in the changes, I can review either or both PRs.

We will close this PR after some testing.

**Comment by Dillon-Dumesnil** [comment]
Okay, that sounds good. In the future, it would be helpful if you were able to make this as a draft PR which I believe still runs tests, but does not alert our team to review it. Thanks for letting me know Awais!

**Comment by awais786** [comment]
@Dillon-Dumesnil we are just checking discovery behaviour on django2.2. We will close it soon.

**Pull request closed without merging**
