### PR TITLE
Added copy icon on course about read only page.

### PR DESCRIPTION
**Pull request by waheedahmed**
ECOM-5205

### CODE REVIEW

**Comment by waheedahmed** [comment]
@bderusha Please review this.

@awais786 You can use font-awesome icon classes in your PR for edit comments when this PR is merged into master.

screen shot 2016-08-10 at 5 52 32 pm

**Comment by awais786** [comment]
👍

**Comment by waheedahmed** [comment]
@ahsan-ul-haq Please review this.

**Comment by ahsan-ul-haq** [comment]
👍

**Pull request merged**
