### PR TITLE
Search: courses and course runs

### PR DESCRIPTION
**Pull request by clintonb**
The API now exposes endpoints for searching courses and course runs.

ECOM-4747

### CODE REVIEW

**Comment by clintonb** [comment]
@bderusha @Dillon-Dumesnil @AlasdairSwan please review
FYI @edx/ecommerce

**Comment by rlucioni** [comment]
@clintonb I took a quick look and didn't see anything about caching. Are you considering caching search queries/results in the future?

**Comment by Dillon-Dumesnil** [comment]
Looks good

**Comment by rlucioni** [comment]
Relatedly, are there plans to load test this? It would really help assess the need for/benefit of caching.

**Comment by clintonb** [comment]
@rlucioni caching and load testing will come later. This is just the API.

**Pull request merged**
