### PR TITLE
feat: use select_related to fetch types in CSVLoader

### PR DESCRIPTION
**Pull request by Ali-D-Akbar**
[PROD-4237](https://2u-internal.atlassian.net/browse/PROD-4237)
Adds select_related to Eager load CourseType and CourseRunType for Courses and CourseRuns respectively in CSVLoader

### CODE REVIEW

**Review by AfaqShuaib09 — APPROVED** [review]

**Comment by AfaqShuaib09** [comment]
nit: commit type can be `perf` instead of `feat`

**Review by DawoudSheraz — COMMENTED** [review]
do we have stats on how does this improve the overall filtering?

**Comment by Ali-D-Akbar** [comment]
> do we have stats on how does this improve the overall filtering?

```
>>> # Without select_related
>>> start_time = time.time()
>>> course = Course.objects.filter_drafts(key='edX+DemoX').first()
>>> if course:
...     uuid = str(course.type.uuid)  # This triggers an additional query
... 
>>> end_time = time.time()
>>> print(f"Without select_related: {end_time - start_time:.4f} seconds")
Without select_related: 0.0395 seconds
>>> 
>>> # With select_related
>>> start_time = time.time()
>>> course = Course.objects.filter_drafts(key='edX+DemoX').select_related('type').first()
>>> if course:
...     uuid = str(course.type.uuid)  # No additional query
... 
>>> end_time = time.time()
>>> print(f"With select_related: {end_time - start_time:.4f} seconds")
With select_related: 0.0058 seconds
```

**Review by DawoudSheraz — APPROVED** [review]
While it does not achieve much individually but it might prove a bit helpful when running loader against large set of data.

**Pull request merged**
