### PR TITLE
Change edx-django-release-util version.

### PR DESCRIPTION
**Pull request by doctoryes**
Change the required version of edx-django-release-util to 0.1.1.

@edx/ecommerce Please review and tag appropriate parties.

### CODE REVIEW

**Comment by clintonb** [comment]
👍

**Comment by rlucioni** [comment]
👍

**Comment by doctoryes** [comment]
@clintonb @rlucioni Just to be pedantic: instead of rebasing this PR, I hit the GitHub "Merge master into this branch" button. This method appears to have worked - but if you'd rather that I'd rebased instead of merged, I'll do this over. Comments?

**Comment by rlucioni** [comment]
@doctoryes we tend to rebase to keep the commit history clean.

**Comment by doctoryes** [comment]
Ok - rebased - merging now...

**Pull request merged**
