### PR TITLE
Use weak password hashing for testing in course-discovery 

### LINKED ISSUE #164: Use weak password hashing for testing in course-discovery
We can improve the total time of the test suite by choosing a weak password hasher for the test environment only. 

Ref: https://docs.djangoproject.com/en/4.1/topics/testing/overview/#password-hashing

### PR DESCRIPTION
**Pull request by joelantoniov**
## Description

This pull request addresses the issue regarding slow test suite performance caused by strong password hashing during testing. To improve the test suite runtime, I have implemented a solution that uses weak password hashing specifically for testing purposes, as recommended by the Django documentation: https://docs.djangoproject.com/en/4.1/topics/testing/overview/#password-hashing

## Changes Made

- Created a new test file `course_discovery/settings/test_weak_password.py` to implement weak password hashing for testing.
- Modified the test settings to use the weak password hashing configuration only during testing.
- Added a test case to verify that weak password hashing is applied during testing.

This change has been tested locally and successfully improves the test suite runtime while ensuring the security of strong password hashing in production.

Fixes: https://github.com/openedx/public-engineering/issues/164

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @joelantoniov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
Hi @joelantoniov, we need to have a valid Contributor License Agreement (CLA) in place for all contributions.  See the welcome message above for the details about how to enroll.  The process is different depending upon whether you are making this contribution as an individual or on behalf of your employer.

**Comment by e0d** [comment]
@joelantoniov The CLA issue is resolved, but looks like there's an import/dependency problem.  Can you have a look?

```
validator_config = [{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'}, {'NAME': 'django.contrib.auth.p..._validation.MinimumLengthValidator'}, {'NAME': 'django.contrib.auth.password_validation.UnsaltedMD5PasswordValidator'}]

    def get_password_validators(validator_config):
        validators = []
        for validator in validator_config:
            try:
                klass = import_string(validator['NAME'])
            except ImportError:
                msg = "The module in NAME could not be imported: %s. Check your AUTH_PASSWORD_VALIDATORS setting."
>               raise ImproperlyConfigured(msg % validator['NAME'])
E               django.core.exceptions.ImproperlyConfigured: The module in NAME could not be imported: django.contrib.auth.password_validation.UnsaltedMD5PasswordValidator. Check your AUTH_PASSWORD_VALIDATORS setting.

.tox/py38-django32/lib/python3.8/site-packages/django/contrib/auth/password_validation.py:29: ImproperlyConfigured
```

**Comment by e0d** [comment]
@joelantoniov also, can you link to the recommendation in the Django docs to speed up review.

**Comment by joelantoniov** [comment]
> @joelantoniov also, can you link to the recommendation in the Django docs to speed up review.

Hi, @e0d ! I already done what you have mentioned. I modified description and I added the documentation link required. I am awaiting that github runs my last commit since a few days ago.

**Comment by e0d** [comment]
@joelantoniov , I notice there are some commit-lint failures.  Please note that we use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard? 

All of the commit messages for commits in the PR need to follow the standard.

**Comment by joelantoniov** [comment]
> @joelantoniov , I notice there are some commit-lint failures. Please note that we use conventional commits across Open edX projects. You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type). Can you please amend your commit messages to follow our standard?
> 
> All of the commit messages for commits in the PR need to follow the standard.

@e0d Howver, my last message commit was "style: improve the styling of the code.", which follows the standard according to the documentation.

**Comment by openedx-webhooks** [comment]
@joelantoniov Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/4065&entry.1484655318=https://github.com/joelantoniov&entry.752974735=2023-08-22+16:05&entry.1917517419=2023-08-29+15:04&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
