### PR TITLE
Displaying social links and major works on view instructor on publish…

### PR DESCRIPTION
**Pull request by Dillon-Dumesnil**
…er course run page

### CODE REVIEW

**Comment by Dillon-Dumesnil** [comment]
image

**Comment by Dillon-Dumesnil** [comment]
One weird thing is that the `Straight HTML?` is actually `<h1>Straight HTML? </h1>`, and if you hit the copy, it will copy the HTML tags. Not sure what desired behaviour there is.

**Review by mikix — APPROVED** [review]
Nice CSS cleanup. I might personally have a little less space between the social links (use a br instead of p maybe?) but that's just a matter of taste. Love it!

**Comment by Dillon-Dumesnil** [comment]
image

**Pull request merged**
