### PR TITLE
Accessing the Discovery Service Super Admin

### PR DESCRIPTION
**Pull request by chinmaybhatk**
Creating/Accessing the Discovery Service Super Admin to create the catalogues and many more

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @chinmaybhatk! I've created [OSPR-4374](https://openedx.atlassian.net/browse/OSPR-4374) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Review by mikix — APPROVED** [review]
Sure, thank you for the patch!

**Comment by mikix** [comment]
Some flaky test failed. I'll push this through anyway.

**Comment by openedx-webhooks** [comment]
@chinmaybhatk 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/2529&entry.1484655318=https://github.com/chinmaybhatk&entry.752974735=2020-04-10+06:46&entry.1917517419=2020-04-10+12:41&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@chinmaybhatk Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your code contributions. Please send it as soon as possible, as we won't be able to keep your code in our platform unless the agreement is signed.

**Comment by natabene** [comment]
@chinmaybhatk Have you had a chance to sign our agreement? Please sign it as soon as possible, as we will need to revert this PR if we don't receive the signed agreement soon.

**Comment by chinmaybhatk** [comment]
Thanks for this nudge.

Because of covid lock down I'm unable to take a print and sign, scan and
send back to you.

Is it OK if I attach picture of my sign on the document and send it back to
you?

**Comment by natabene** [comment]
@chinmaybhatk Of course, please take a picture and send to legal@edx.org.

**Comment by natabene** [comment]
@chinmaybhatk Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Pull request merged**
