### PR TITLE
Added Custom migration for user model

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**
A custom migration needs to be created in Django 1.10 for the user model inherided from AbstractUser

### CODE REVIEW

**Comment by ahsan-ul-haq** [comment]
My apology for missing this part while updating Django to 1.10.7. @rlucioni thanks for pointing this out.

**Review by clintonb — APPROVED** [review]
No need to apologize. We need to do a better job of detecting missing migrations. This can be done by running `./manage.py makemigrations --check --dry-run`.

**Comment by clintonb** [comment]
I have filed [LEARNER-1085](https://openedx.atlassian.net/browse/LEARNER-1085) to update Travis to detect missing migrations.

**Review by rlucioni — APPROVED** [review]
Please remember to squash your commits!

**Pull request merged**
