### PR TITLE
OEP-5 Compliance 

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
TODO: http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0005.html
- [x] Move data to `.dev/`
- [x] Update `.gitignore`
- [x] Update `.dockerignore`

**Comment by clintonb** [comment]
FYI @edx/ecommerce

**Comment by schenedx** [comment]
👍

**Comment by clintonb** [comment]
@cpennington I'm only doing the data changes now. Too much doing on to update the `Makefile`. Any other changes, besides those listed, needed for compliance with OEP-5?

**Comment by rlucioni** [comment]
👍

**Comment by rlucioni** [comment]
Not sure what's up with the test failure. I'd be surprised if we had a flaky unit test.

**Pull request merged**
