### PR TITLE
bug fix and install cors middleware

### PR DESCRIPTION
**Pull request by armbox**
- bug fix in update_index command 
- install cors middleware.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @armbox! I've created [OSPR-2840](https://openedx.atlassian.net/browse/OSPR-2840) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@armbox  Thank you for your contribution. We will review once contributors agreement has been processed by our team.

**Comment by natabene** [comment]
@armbox We have added your user to our records and can now review your code going forward. I will queue this for engineering review.

**Comment by mikix** [comment]
@armbox hello! Looks like we did the cors part separately since you proposed this PR. So good idea there :) But it can be dropped from this PR.

That would still leave the index fix. I don't quite understand the problem there? But I assume there is one.

**Comment by armbox** [comment]
@mikix  backend.index_name is initialized in "self.prepare_backend_index(backend)", so one need to call the prepare_backend_index(backend) before access the backend.index.

**Comment by mikix** [comment]
Well, here's `prepare_backend_index`:

```
        alias = backend.index_name
        index_name = ElasticsearchUtils.create_index(backend.conn, alias)
        backend.index_name = index_name
        return alias, index_name
```
 
So backend.index_name *does* have content before calling prepare_backend_index it looks like. It just gets overriden by that call. And then the old value is returned as a recommended alias for the new index, presumably because something might have referenced the old name already?

Is there an actual bug symptom caused by referencing the original name before it gets overriden by `prepare_backend_index`, or is this a cleanliness PR?

**Comment by armbox** [comment]
Thanks for the review,
I'll revisit when it cause problem again.

Thanks,

**Comment by openedx-webhooks** [comment]
@armbox Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/1623&entry.1484655318=https://github.com/armbox&entry.752974735=2018-11-28+10:15&entry.1917517419=2019-03-12+06:13&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
