### PR TITLE
Updated taxonomy version

### PR DESCRIPTION
**Pull request by HammadAhmadWaqas**

### CODE REVIEW

**Review by saleem-latif — APPROVED** [review]

**Review by waheedahmed — APPROVED** [review]
Just one question does this requirement's version is not being updated through our regular Python requirement upgrade job?

**Comment by HammadAhmadWaqas** [comment]
This requirement's version was updated through our regular Python requirement upgrade job. (These are not updated manually.)

**Comment by waheedahmed** [comment]
@HammadAhmadWaqas I mean, there is a scheduled job in Jenkins which runs every week and updates the Python requirements to their latest available versions. If it was created by that job the committer should be @edx-requirements-bot but not you. For an example check this PR https://github.com/edx/course-discovery/pull/2973

**Comment by HammadAhmadWaqas** [comment]
@waheedahmed Sorry I miss understood. I thought we are talking about the `make upgrade` command.
Actually, we needed this upgrade urgently which is why we created this dump PR.

**Pull request merged**
