### PR TITLE
feat: :white_check_mark: generate test data for devstack

### PR DESCRIPTION
**Pull request by edx-abolger**
This PR creates a management command that creates test Course and Course Run data with Partner and source URLs pointed at devstack. The goal of the command is to enable automatic data generation that can easily be scripted for use with other devstack data.

### CODE REVIEW

**Comment by waheedahmed** [comment]
@edx-abolger There is already a command `create_test_program` available which also creates some course and course runs alongside a program, could we use that instead?

**Comment by edx-abolger** [comment]
> @edx-abolger There is already a command `create_test_program` available which also creates some course and course runs alongside a program, could we use that instead?

So that test script is missing base factory data requirements that are necessary in the test data in order for Enterprise developers to use the created data.  I am amenable to changing that script to create the data that Enterprise courses specifically need for fast development, but it does have different behaviors. Options to clarify this:
1.  changing the name of this script to 'seed_enterprise_devstack_data.py', which would follow the convention used in other repos, 
or 
2.  changing the data created by create_test_program, which I did not want to do without consulting existing users as it would change course behavior (adding runs, adding other data, and also automatically creating published courses).  I am completely fine with doing that if we can be assured it won't break the workflow of other developers or sandboxes that may use the existing commands.
3. Option (2) but with a flag that only makes all the extra status changes if you specify --enterprise-ready or something similar

**Review by waheedahmed — COMMENTED** [review]
@edx-abolger The 3rd option seems reasonable to me but since this is for only test data, I believe we are good here with a separate command as well. Just add some test cases for this new command. Thanks!

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @edx-abolger! I've created [OSPR-6499](https://openedx.atlassian.net/browse/OSPR-6499) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by johnnagro** [comment]
Moving this work to https://github.com/openedx/course-discovery/pull/3312

**Comment by openedx-webhooks** [comment]
@edx-abolger Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3089&entry.1484655318=https://github.com/edx-abolger&entry.752974735=2021-08-12+17:20&entry.1917517419=2022-03-02+16:21&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
