### PR TITLE
Updated Django Waffle to 0.12.0

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/learner

**Comment by schenedx** [comment]
@clintonb Looks like some management command teardown is broken?

**Comment by nedbat** [comment]
If this is important for Ginkgo, it will have to be cherry-picked.

**Comment by nedbat** [comment]
What's the status of this?

**Comment by clintonb** [comment]
@nedbat I doubt this will land anytime soon. @schenedx does your team have capacity to resolve this issue?

**Comment by schenedx** [comment]
@clintonb Not at the moment. And frankly, I don't even remember the context here. Can I get some in this PR?

**Comment by clintonb** [comment]
The Django 1.11 upgraded was pushed out with a version of Django Waffle that is not fully compatible with Django 1.11—management commands don't work. This PR upgrades Django Waffle; however, there is an issue with a test resulting in MySQL going away.

**Comment by nedbat** [comment]
This PR is mentioned on the Ginkgo wiki page. I'll mark it there as deferred. Thanks.

**Pull request closed without merging**
