### PR TITLE
Don't push draft data to ecommerce

### PR DESCRIPTION
**Pull request by mikix**
We'll add pushing to ecommerce back once we have a review flow. Then, once successfully reviewed, a course's ecommerce data will be updated or created.

### CODE REVIEW

**Review by Dillon-Dumesnil — CHANGES_REQUESTED** [review]
Now that we won't be storing the sku, the `update_entitlements` function should be updated to not check for that. Might need to verify that the CourseEntitlement serializer doesn't freak out about that, but if it does, calling update directly would be a fix.

Secondary question, should we update the ecommerce api updates we made or leave those for when we want to use them?

**Comment by mikix** [comment]
Ugh great point abut sku. Removed. I think we can keep the ecommerce API changes in, yeah? We'll need em soon.

**Comment by Dillon-Dumesnil** [comment]
I'm happy to leave them, just want to make sure it's a conscious decision and not because we forgot about them.

**Review by Dillon-Dumesnil — APPROVED** [review]
Beautiful. Just wish there was one more line to delete so you could hit that nice 200 deletions

**Pull request merged**
