### PR TITLE
Implement tabs design for the dashboard page. Adding sass.

### PR DESCRIPTION
**Pull request by awais786**
Implement the backend to save course run key in pending studio instances and send an email to course team with subject "Studio instance created".

ECOM-6178

### CODE REVIEW

**Comment by awais786** [comment]
@ahsan-ul-haq Please review this PR. 
This is already reviewed from Lahore/Cambridge team.
https://github.com/edx/course-discovery/pull/410

But for safe side it is good to review this PR.

**Comment by awais786** [comment]
I have created a ticket for bcc implementation.
https://openedx.atlassian.net/browse/ECOM-6348

**Comment by awais786** [comment]
@bderusha with django-ses we need one to=[email id] otherwise it throws an error. Please tell me what to do in this situation.  We need one email in to. May be we can use the from_email_id here too.  I have created the separate ticket also this. Should we merge this PR without bcc ?

**Comment by awais786** [comment]
I have tried that and it looks good.
`EmailMultiAlternatives(
            subject, plain_content, from_address, to=[settings.PUBLISHER_FROM_EMAIL], bcc=to_addresses
        )`

**Comment by awais786** [comment]
screen shot 2016-11-11 at 7 55 53 pm

I have implemented that in this PR.

**Comment by awais786** [comment]
@bderusha This PR is already reviewed in old PR https://github.com/edx/course-discovery/pull/410 of waheed. 
I created this PR because old PR was against my branch and I have merged that one in master.

**Review by bderusha — APPROVED** [review]

**Pull request merged**
