### PR TITLE
[SE-3515] Handle JSON decoder error if api fails

### PR DESCRIPTION
**Pull request by pkulkark**
This PR ports #2793 to master branch. It handles the JSON decoder error that is seen if the program api returns 404 when running refresh_course_metadata command. It checks the status code of the response before calling the json() method.

**Jira Tickets:** [OSPR-5363
](https://openedx.atlassian.net/browse/OSPR-5363)
**Testing Instructions:**
- Ensure no programs are indexed. Running the command `/edx/bin/manage.discovery update_index --disable-change-limit` should show 0 programs.
- Run command `/edx/bin/manage.discovery refresh_course_metadata`.
- Verify command succeeds without any errors.

**Reviewers:**

- [ ] @Dillon-Dumesnil

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pkulkark! I've created [OSPR-5363](https://openedx.atlassian.net/browse/OSPR-5363) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by Dillon-Dumesnil — APPROVED** [review]

**Comment by Dillon-Dumesnil** [comment]
See conversation in https://github.com/edx/course-discovery/pull/2793 for context

**Comment by openedx-webhooks** [comment]
@pkulkark 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/2889&entry.1484655318=https://github.com/pkulkark&entry.752974735=2021-01-15+06:18&entry.1917517419=2021-01-15+11:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@pkulkark Thank you for your contribution!

**Pull request merged**
