### PR TITLE
WIP Filter program list by partner short code

### PR DESCRIPTION
**Pull request by douglashall**
Allows for filtering of the program list API endpoint by
partner short code using a partner_short_code query parameter.

### CODE REVIEW

**Comment by clintonb** [comment]
The service has pretty much everything it needs to facilitate multi-tenancy except updated API endpoints. It would be preferable to complete that functionality rather than add filtering ad hoc.

**Comment by douglashall** [comment]
@clintonb I'm not sure what you mean. Do you have a document that explains how you expect multi-tenancy to work for the catalog service? At the moment, I'm most interested in understanding how you would expect an Open EdX site to display programs specific to that site.

**Comment by clintonb** [comment]
All of the data is linked to a partner. What is missing for multi-tenancy is linking the partners to sites, and automatically filtering the data at the API endpoints by the requesting site's partner. If we do that, we solve this problem all of the data—courses, programs, organizations, people.

**Comment by douglashall** [comment]
@clintonb Awesome. Have you talked with @mjfrey about planning that work? It will be required for the program certs enablement.

**Comment by clintonb** [comment]
No. I am not actively working on certificates.

**Pull request closed without merging**
