### PR TITLE
Resolved issue with broken tests

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/learner

**Comment by schenedx** [comment]
@clintonb How did you find out updating libraries will solve this issue?

**Review by schenedx — APPROVED** [review]
👍

**Review by rlucioni — APPROVED** [review]
@clintonb nice, thank you for jumping on this! @MatthewPiatetsky FYI.

**Comment by clintonb** [comment]
@schenedx I searched for the error message on Google. Always start with the simple solution.

**Pull request merged**
