### PR TITLE
ENT-3334 | SAP SF customer is seeing courses as not open for enrollment when they should be

### PR DESCRIPTION
**Pull request by HammadAhmadWaqas**
added status in CourseSearchSerializer to get status on search/all endpoint.
this status will be used to check the availability of the course.

### CODE REVIEW

**Review by hasnain-naveed — APPROVED** [review]
LGTM

**Review by Dillon-Dumesnil — DISMISSED** [review]
Sure

**Comment by Dillon-Dumesnil** [comment]
So I just want to get some clarity on how this status can help/how it will be used to understand if this is the correct fix. Thank you!

**Review by muhammad-ammar — APPROVED** [review]

**Comment by HammadAhmadWaqas** [comment]
@Dillon-Dumesnil actually we make decisions about the `course` using its course runs information, that information includes its `enrollment_start` `enrollment_end` `availability` as well as its `status`. if all that information is valid then we say that course is active.
Here is [PR](https://github.com/edx/edx-enterprise/pull/795) that first time tried to use `status` for deciding `active` value.

**Review by Dillon-Dumesnil — APPROVED** [review]
Ah right, I forgot we show stuff at the Course level and not Course Run level so you're able to aggregate information. Sounds good.

**Pull request merged**
