### PR TITLE
Prototype code for import course-metadata courses into publisher app.

### PR DESCRIPTION
**Pull request by awais786**
**WIP: This Code is just for team review will not be merge into master.**
This PR contains Prototype code for importing course-metadata into publisher app.

1. I made some changes in code instead of using any organizaion i think its good to do this in batches. e.g start_id = 1 to end_id= 500
2. Second the right mapping of fields.

ECOM-7712

Following ticket contains detailed information.
https://openedx.atlassian.net/browse/ECOM-7755

### CODE REVIEW

**Comment by awais786** [comment]
@bderusha what do think about this PR. I want to discuss this with you next week also.

**Comment by awais786** [comment]
**Fields Mapping questions**
Metadata has authoring_organizations and sponsoring_organizations. But publisher has only organizations. So which organization from metadata will go into publisher and it should be one only?

**Comment by awais786** [comment]
Is there any field in metadata for course-image ? I did't find any one.

**Comment by clintonb** [comment]
https://github.com/edx/course-discovery/blob/master/course_discovery/apps/course_metadata/models.py#L277

**Comment by awais786** [comment]
In course table there is a URL field card_image_url. We don't have any field in publisher to save this field. We have image field which saves the image as file. So i think we need to add another URL field to save this value.

**Pull request closed without merging**
