### PR TITLE
Added FAQ, Video link and learner testimonial fields in course edit form.

### PR DESCRIPTION
**Pull request by waheedahmed**
[ECOM-7618](https://openedx.atlassian.net/browse/ECOM-7618)

**AC:**
1. Validate the video link is only available to edX Internal users (PC, Marketing, Publisher) on course edit page
2. Validate the course edit form has the FAQ and Learner testimonial fields for data entry for all users

screencapture-localhost-8004-publisher-courses-33-edit-1491375832255

### CODE REVIEW

**Comment by waheedahmed** [comment]
@tasawernawaz @awais786 Please review.

**Review by tasawernawaz — APPROVED** [review]
I think we need `example` and `best practices` tabs with newly added fields on edit page. 
You can ask from prod team or may be we can create a subtask/new ticket.

**Comment by waheedahmed** [comment]
@tasawernawaz Yeah, I already asked Deen about them.

**Comment by waheedahmed** [comment]
@tasawernawaz Please take anpther look, added best practices and examples.

@awais786 Please review.

**Review by tasawernawaz — APPROVED** [review]

**Review by awais786 — APPROVED** [review]

**Pull request merged**
