### PR TITLE
Avoid bad string decode call

### PR DESCRIPTION
**Pull request by jmyatt**
https://openedx.atlassian.net/browse/DISCO-1701

### CODE REVIEW

**Review by Dillon-Dumesnil — COMMENTED** [review]
Going to wait to approve until we figure out what's happening with the tests.
And looking at the ticket, perhaps the issue is that this one course is somehow returning a list instead of a string?

**Comment by jmyatt** [comment]
the test failures are related to the code change (bytestring / unicode string conversion) so before I change the test I need to make sure that's the right thing to do.  The list being returned is in the Exception's `content` attr, but a similar error occurs with that attr contains a unicode string instead of a list (in that case the error is `'str' object has no attribute 'decode'`)

**Comment by mikix** [comment]
Is it possible that python3 guarantees `e.content` is a unicode string if it exists? If so, we can simply drop the `decode` call.

**Comment by jmyatt** [comment]
that's what I tried first, but some tests failed due to the fact that they explicitly set bytestrings in that `content` attr.  So I took this approach to cover the case where we might actually get a bytestring in runtime.  But maybe the test should just be changed?  

the test lines I'm referring to:
https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/v1/tests/test_views/test_courses.py#L932
https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/v1/tests/test_views/test_course_runs.py#L618

**Comment by mikix** [comment]
What exception class is hitting this code path? (i.e. what library is the exception type that provides `content`? I looked real quick at django and drf, but didn't see exceptions like that)

**Comment by jmyatt** [comment]
yes good point - it's unclear which Exception class this is since the AttributeError on the decode call is happening in the `except` block for the original Exception.  I'll change this PR to temporarily log that information, then will be able to follow up with another change to clean it up.

**Review by mikix — APPROVED** [review]

**Pull request merged**
