### PR TITLE
Awais786/ecom 5880 org metadata

### PR DESCRIPTION
**Pull request by awais786**
WIP:

### CODE REVIEW

**Comment by awais786** [comment]
screen shot 2016-11-09 at 11 40 30 pm

This is main Organization admin page. Inline functionality is implemented here.

**Comment by clintonb** [comment]
@awais786 @bderusha is there roles/permissions document available for review?

**Comment by bderusha** [comment]
@awais786 can we close this?

**Comment by bderusha** [comment]
@awais786 I am closing this PR.  Please reopen if you think it should remain open.

**Pull request closed without merging**
