### PR TITLE
Adding areas of expertise UI changes. Removing areas of expertise from

### PR DESCRIPTION
**Pull request by Dillon-Dumesnil**
the marketing site data loader.

### CODE REVIEW

**Comment by Dillon-Dumesnil** [comment]
This is not off of master, but off of ddumesnil/areas-of-expertise and will need to be rebased before merging

**Comment by Dillon-Dumesnil** [comment]
Okay, this is actually ready for review now. That was dumb trying to put it up early. My bad

**Comment by Dillon-Dumesnil** [comment]
Depends on https://github.com/edx/edx-mktg/pull/2737

**Review by mikix — APPROVED** [review]
Sure. I'll defer to Alasdair for the UI stuff, but this looks reasonable to me.

**Comment by Dillon-Dumesnil** [comment]
Spoke with @AlasdairSwan about UI changes in person. Most recent push regards his requested changes.

**Pull request merged**
