### PR TITLE
Pulling the course start/end dates from Drupal

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-4543

### CODE REVIEW

**Comment by clintonb** [comment]
@bderusha or @peter-fogg please review

**Comment by peter-fogg** [comment]
👍

**Comment by bderusha** [comment]
Do we also need to remove this assignment from course API data loader

**Comment by clintonb** [comment]
@bderusha It's fine if we keep the Course API loader. That way, we have it as a default. Since the Drupal API loader runs last, it's data wins.

**Pull request merged**
