### PR TITLE
Upgraded to jQuery 3.2.1

### PR DESCRIPTION
**Pull request by clintonb**
This avoids a security vulnerability in older versions.

LEARNER-456

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/fedx-team

**Comment by attritionorg** [comment]
Upgrading from 3.1.1 to 3.2.1, can you clarify which jQuery vulnerability this addresses?

**Comment by clintonb** [comment]
https://openedx.atlassian.net/wiki/display/EdxOps/jQuery+XSS+vulnerability+discovery+and+recommendations

This service was actually not affected since we have always used jQuery 3.x.

**Comment by attritionorg** [comment]
Unfortunately that requires authentication. If it references the recent: https://nodesecurity.io/advisories/329, that is fixed by 1.9.0 and presumably doesn't impact later trees. That is what made me curious.

**Pull request merged**
