### PR TITLE
Publishing instructors to Drupal on creation in publisher

### PR DESCRIPTION
**Pull request by Dillon-Dumesnil**

### CODE REVIEW

**Review by mikix — APPROVED** [review]
You'll need to update translations. But yeah, :shipit:

**Comment by Dillon-Dumesnil** [comment]
That's annoying. It told me it was fine locally. Also, someone merged in between your comment and when I force pushed. Curses

**Comment by mikix** [comment]
Oh I might be wrong then. I had assumed "New" wasn't elsewhere in the source code.

**Comment by Dillon-Dumesnil** [comment]
It's real weird. /shrug The detect_changed_source_translations passed locally, but then fake_translations still added new ones so I dunno. They're there. It should pass?

**Pull request merged**
