### PR TITLE
Default to populate max_effort with only 1 effort value present

### PR DESCRIPTION
**Pull request by McKenzieW**
When only one value  -- as opposed to a range -- is provided for estimated effort for a course run in Drupal, use this to populate max_effort for the course in Discovery instead of min_effort.

The presence of max_effort as opposed to min_effort in Discovery will allow for the calculation of Hours of Effort for course certificates having this feature enabled.

[LEARNER-3220](https://openedx.atlassian.net/browse/LEARNER-3220)

### CODE REVIEW

**Review by waheedahmed — APPROVED** [review]

**Comment by waheedahmed** [comment]
@McKenzieW Zubair is out for two days you can ask someone else for review.

**Review by bderusha — APPROVED** [review]

**Review by clintonb — APPROVED** [review]
Why not update whichever client is using this data to fallback to `min_effort` if `max_effort` is not available?

**Comment by McKenzieW** [comment]
@clintonb you're passing some mixed messages with PR approval and suggestion of an alternative approach

**Comment by clintonb** [comment]
Acknowledged. I'm still curious as to whether that solution was explored.

**Comment by McKenzieW** [comment]
It would involve caching extra data

**Pull request merged**
