### PR TITLE
BB-900: Save card_image_url in the correct model when loading data

### PR DESCRIPTION
**Pull request by giovannicimolin**
This PR fixes a small bug on the discovery service where the data loader would incorrectly save `card_image_url` to the incorrect model, resulting in courses with missing course images on services that use the discovery service (e.g. ecommerce).

**Testing instructions:** Sandbox not provisioned yet.

**Testing instructions:**
1. Checkout this branch on your devstack
2. Log into the course discovery shell with `make discovery-shell` and updated the course metadata:
```
./manage.py refresh_course_metadata
```
3. Go to http://localhost:18130/basket/add/?sku=8CF08E5 and check that the course image is being correctly displayed.
its_there_now

**Reviewers:**
- [ ] @kaizoku 
- [x] EdX Reviewer TBD

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-3100](https://openedx.atlassian.net/browse/OSPR-3100) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@giovannicimolin Thank you for your contribution.

**Comment by natabene** [comment]
@dianakhuang Can you give this a look?

**Review by dianakhuang — APPROVED** [review]
This looks good to me. Thanks for catching this!

**Comment by natabene** [comment]
@dianakhuang  Thanks for approving, can you also merge it? Community contributors don't have permissions to merge.

**Comment by openedx-webhooks** [comment]
@giovannicimolin 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/1790&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2019-02-20+18:23&entry.1917517419=2019-02-21+18:40&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
