### PR TITLE
small PR to add the type slug to the Program response

### PR DESCRIPTION
**Pull request by staubina**
Small PR to add the slug for Program Type.

### CODE REVIEW

**Review by kdmccormick — APPROVED** [review]
Looks good :+1: 

You're obviously more in-tune with the architecture of this API than I am, but there may benefit to deprecating the `type` field or otherwise making it clear that `type_slug` is preferred. Take that as you will -- not a blocking issue.

**Comment by staubina** [comment]
Deprecating fields is more difficult than adding fields to an API because of the potential for breaking the contract with users.

I think we need to form a V2 of this API eventually and slowly add to it what is used and needed rather than deprecating fields.

@kdmccormick thanks for the review 👍

**Review by jlajoie — APPROVED** [review]
👍

**Comment by mikix** [comment]
In the future, we've been trying to move towards using uuids more often for this sort of thing. Especially across services, where renaming things is nigh-impossible.

CourseTypes and CourseRunTypes are referenced by UUID in our serializers. ProgramType ought to as well (though that would involve adding a uuid field to the model).

**Pull request merged**
