### PR TITLE
Upgrade django to 1.11

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**
LEARNER-947

### CODE REVIEW

**Comment by clintonb** [comment]
Did you run `makemigrations` to ensure we didn't miss anything?

**Comment by ahsan-ul-haq** [comment]
Yes I ran that and it was showing `No changes detected`

**Review by clintonb — APPROVED** [review]

**Review by schenedx — APPROVED** [review]
LGTM

**Comment by schenedx** [comment]
Verified on stage. Looks good

**Pull request merged**
