### PR TITLE
WS-1143: adding degree.micromasters_path to discovery

### PR DESCRIPTION
**Pull request by JackedX**
checking degree micromasters_url is a string before calling regex for…… micromasters_path in serializer.js

### CODE REVIEW

**Review by Dillon-Dumesnil — APPROVED** [review]

**Review by srwang — APPROVED** [review]
what was the issue?

**Comment by JackedX** [comment]
> what was the issue?

I needed to check that the degree.micromasters_url was a string before calling regex functions

**Comment by rgraber** [comment]
Do we know under what circumstances it's not a string?

**Comment by JackedX** [comment]
> Do we know under what circumstances it's not a string?

I coded and tested for the two following conditions
1. There are micromasters without micromasters_url
2. Programs without degrees

**Pull request merged**
