### PR TITLE
Fixed JS requirement issue.

### PR DESCRIPTION
**Pull request by waheedahmed**
@bderusha @awais786 Please review.

### CODE REVIEW

**Comment by awais786** [comment]
👍

**Comment by bderusha** [comment]
👍

**Comment by clintonb** [comment]
`requirements.js` (plural) should be used to keep all of our IDAs aligned. We aren't using the singular version anywhere else.

**Comment by bderusha** [comment]
@clintonb agreed.  But we need to be more strategic about the change.  This was added without a corresponding configuration change.  We will update this is all of the proper places as part of fixing the static asset issue

**Pull request merged**
