### PR TITLE
jwt coverage

### PR DESCRIPTION
**Pull request by bderusha**
@clintonb @peter-fogg

### CODE REVIEW

**Comment by peter-fogg** [comment]
Code looks good in 4afa44e3c7fdddaf036d03892fc806cd22bb2298. But why does the JWT generation need to be done in a mixin? None of the methods actually use the `self` parameter, so it could just be a collection of functions in a module.

**Comment by bderusha** [comment]
@peter-fogg updated.

**Comment by peter-fogg** [comment]
:+1:

**Comment by clintonb** [comment]
:+1: Please file a ticket to extract the JWT code into edx-drf-extensions, where it belongs.

**Pull request merged**
