### PR TITLE
Update advanced.rst

### PR DESCRIPTION
**Pull request by eddiebarry**
There is ambiguity between 
"client id" and ``SOCIAL_AUTH_EDX_OAUTH2_KEY`` and the 
"client secret"  and ``SOCIAL_AUTH_EDX_OAUTH2_SECRET`` values.

personally wasted a lot of time on this

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @eddiebarry! I've created [OSPR-5642](https://openedx.atlassian.net/browse/OSPR-5642) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@eddiebarry Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by eddiebarry** [comment]
[Individual_Contributor_Agreement_Edgar_Monis_.pdf](https://github.com/edx/course-discovery/files/6062607/Individual_Contributor_Agreement_Edgar_Monis_.pdf)
Sure @natabene Heres the agreement :

**Comment by eddiebarry** [comment]
Sure @natabene, I've sent the document in to your legal team at legal@edx.org

**Comment by natabene** [comment]
@wajeeha-khalid Could you review this?

**Comment by wajeeha-khalid** [comment]
@waheedahmed ^^
@natabene I will let Waheed review this; he is tech lead for discovery.

**Review by waheedahmed — APPROVED** [review]
Thank you @wajeeha-khalid @natabene!

Changes looks good to me 👍

**Comment by openedx-webhooks** [comment]
@eddiebarry 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/2955&entry.1484655318=https://github.com/eddiebarry&entry.752974735=2021-02-26+08:19&entry.1917517419=2021-03-02+15:02&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
