### PR TITLE
Optimized performance of the Catalog CSV endpoint

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-5534

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/ecommerce please review

**Comment by clintonb** [comment]
The database query count doesn't change much (24 to 21); but, the response time drops from timing out after 60s locally to returning in 4s. In production, this endpoint currently returns in about 23s.

**Comment by rlucioni** [comment]
@clintonb nice, 👍 .

**Comment by schenedx** [comment]
👍

**Pull request merged**
