### PR TITLE
docs: ADR for bringing programs in Publisher

### PR DESCRIPTION
**Pull request by Ali-D-Akbar**
[PROD-3495](https://2u-internal.atlassian.net/browse/PROD-3495)

ADR for adding programs on Publisher for SEO teams. Teams will be able to see programs and edit program slugs on Publisher.

### CODE REVIEW

**Comment by DawoudSheraz** [comment]
shouldn't this ADR be in publisher?

**Comment by Ali-D-Akbar** [comment]
> shouldn't this ADR be in publisher?

I intend to add this in both disco and publisher once the questions are done bcz we're adding functionalities in disco apis for that as well.

**Comment by DawoudSheraz** [comment]
> > shouldn't this ADR be in publisher?
> 
> I intend to add this in both disco and publisher once the questions are done bcz we're adding functionalities in disco apis for that as well.

The publisher ADR should be enough, as this change is more driven towards publisher core and does not impact much on Discovery side.

**Comment by Ali-D-Akbar** [comment]
Closing PR and opening new one in Publisher: https://github.com/openedx/frontend-app-publisher/pull/895/files

**Pull request closed without merging**
