### PR TITLE
Course run and course metadata widget

### PR DESCRIPTION
**Pull request by tasawernawaz**
[ECOM-6072](https://openedx.atlassian.net/browse/ECOM-6072)

**Screenshot**
screen shot 2017-02-16 at 4 45 17 pm

**"empty" will be shown if field is empty**
screen shot 2017-02-16 at 4 45 31 pm

### CODE REVIEW

**Comment by tasawernawaz** [comment]
@waheedahmed @awais786 Please review this.

**Review by waheedahmed — CHANGES_REQUESTED** [review]
Add tests for wrapper properties.

**Comment by tasawernawaz** [comment]
@waheedahmed Test added.

**Review by waheedahmed — APPROVED** [review]
👍 Once build passes.

**Review by awais786 — APPROVED** [review]

**Pull request merged**
