### PR TITLE
Fix CorporateEndorsement prefetching

### PR DESCRIPTION
**Pull request by rlucioni**
endorser is a field on Endorsement, not CorporateEndorsement. We should be prefetching individual_endorsements.

@edx/ecommerce

### CODE REVIEW

**Comment by MatthewPiatetsky** [comment]
👍

**Review by clintonb — APPROVED** [review]
Do query numbers in tests need to be updated?

**Comment by rlucioni** [comment]
@clintonb I'll add a test that includes use of this field. When I missed this earlier, it wasn't caught by tests.

**Comment by clintonb** [comment]
@rlucioni It might be useful to copy the program creation code from the serializer tests to the view tests. This would result in a program with almost all data (except course subjects, I believe).

**Comment by rlucioni** [comment]
@clintonb thanks for the tip. Tests updated.

**Pull request merged**
