### PR TITLE
upgrade edx-drf-extensions to 2.4.4 (take 2)

### PR DESCRIPTION
**Pull request by robrap**
- Upgrade edx-drf-extensions to 2.4.4
- Other upgrades coming with `make upgrade`
- Remove unused JWT_AUTH_REFRESH_COOKIE setting.

ARCH-418, ARCH-1269, ARCH-1044

### CODE REVIEW

**Review by mikix — APPROVED** [review]

**Comment by robrap** [comment]
Thanks @mikix!  Looks like there is an issue due to Discovery's default permission of DjangoModelPermissions.  I will look into it on Tuesday.

**Comment by mikix** [comment]
You may also care about https://github.com/edx/course-discovery/pull/2281/files and its `JWT_AUTH_REFRESH_COOKIE` line in case they merge before you.

**Comment by robrap** [comment]
Thank you @mikix. I added a comment to their PR. We have a ticket on the backlog to do that cleanup, so hopefully search will find anything. I just was getting a head start while I had PRs open anyway.

**Comment by robrap** [comment]
Closing in favor of original PR: https://github.com/edx/course-discovery/pull/2275

**Pull request closed without merging**
