### PR TITLE
Updated preview available email content

### PR DESCRIPTION
**Pull request by clintonb**
- Listing next steps for user to follow
- Links point to the correct locations
- Included note reminding users not to share the URL

EDUCATOR-815

### CODE REVIEW

**Comment by clintonb** [comment]
screencapture-localhost-18381-publisher-email_preview-1505163009215

**Review by muzaffaryousaf — APPROVED** [review]
@clintonb LGTM but i'm not able to find jira ticket that you've mentioned in PR description.

**Comment by clintonb** [comment]
@muzaffaryousaf Try again. The permissions were overly-strict. https://openedx.atlassian.net/browse/EDUCATOR-815

**Comment by muzaffaryousaf** [comment]
Thanks, i can see it now.

**Pull request merged**
