### PR TITLE
Reorganized the data loaders

### PR DESCRIPTION
**Pull request by clintonb**
These files have grown too large. I have split them up to make them a bit more manageable.

ECOM-5099

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/ecommerce

**Comment by rlucioni** [comment]
@clintonb 👍. To make this even easier to work with, you could take the same approach we took with ecommerce's payment processors and put each data loader in its own module.

**Comment by clintonb** [comment]
@rlucioni I'll take that under consideration. Right now the only data loaders I anticipate require additional development are those in the marketing_site package. We may not get much benefit from touching the others.

**Comment by schenedx** [comment]
👍

**Pull request merged**
