### PR TITLE
Add description and destination fields to CreditPathway model

### PR DESCRIPTION
**Pull request by ColeLRogers**
Adds two new fields to the CreditPathway model.

### CODE REVIEW

**Comment by ColeLRogers** [comment]
@yro looks like my migration picked up one of your changes, can you verify?

**Review by dianakhuang — COMMENTED** [review]
Overall, looks good, but I would add/update tests to verify that these fields get rendered out properly by the serializer.

**Comment by yro** [comment]
@ColeLRogers I had to make some changes in my migrations, this must have slipped through the cracks. Feel free to ditch it.

**Review by dianakhuang — APPROVED** [review]
Looks good.

**Pull request merged**
