### PR TITLE
Modified Serializers of api/v1 so that it returns card_image_url…

### PR DESCRIPTION
**Pull request by 2018D**
… of course_metadata instead of image_url which is a property of the model but not a field.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @2018D! I've created [OSPR-2373](https://openedx.atlassian.net/browse/OSPR-2373) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/course-discovery/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by mduboseedx** [comment]
@2018D I apologize for the delay, but could you please sign and send in the Contributor Agreement mentioned in the earlier comment? Once we have that, we can review this PR as well as any future PRs. Thank you for the contribution!

**Comment by mduboseedx** [comment]
@2018D Did you have a chance to send in the Contributor Agreement?

**Comment by 2018D** [comment]
Sorry, I completely forgot until you reminded me. I sent it 5 minutes ago. Thank you for reminding me.

**Comment by mduboseedx** [comment]
@2018D Thanks for sending the agreement!

@edx/learner Is this something you might review?

**Comment by dianakhuang** [comment]
@2018D Sorry for the late response, but is there any chance for you to update your branch and resolve the conflicts?

**Comment by 2018D** [comment]
Hello,

It looks like there's a lot of new features and tests since last year. I haven't used course-discovery since either. I don't believe this pr is still relevant at this point in time. I'll be happy to remake a pr if the need arises once more.

**Comment by openedx-webhooks** [comment]
@2018D Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/1406&entry.1484655318=https://github.com/2018D&entry.752974735=2018-04-25+22:14&entry.1917517419=2019-02-21+20:21&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
