### PR TITLE
Fix character count in publisher, discovery and code clean up.

### PR DESCRIPTION
**Pull request by attiyaIshaque**
### [EDUCATOR-3415](https://openedx.atlassian.net/browse/EDUCATOR-3415)
To fix this issue i have removed [max_lenght](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/course_metadata/models.py#L348)  from **short_description** to keep the sync between [course metadata model Course](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/course_metadata/models.py#L348) and [publisher model Course](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/publisher/models.py#L55). 

Also add `max_lenght_validator` in title to keep the sync between course metadata and publisher.
Clean up some code in **[test_views.py](https://github.com/edx/course-discovery/blob/276ff5eff28bfad33bc2f7b0ff3374557f26019d/course_discovery/apps/publisher/tests/test_views.py)**

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
👍

**Review by awaisdar001 — APPROVED** [review]
Looks good.

**Comment by awaisdar001** [comment]
Please also release to prod after verifying in on stage.

**Comment by attiyaIshaque** [comment]
@awaisdar001  okay :)

**Pull request merged**
