### PR TITLE
ENT-2312 | Adding prefetch_related to for loop to reduce DB queries for seat data

### PR DESCRIPTION
**Pull request by christopappas**
In the `CourseSearchSerializer`, there are two SerializerMethodFields. Within each is a for-loop that iterates over `result.object.course_runs.all()` (I actually didn't notice the 2nd loop until after committed a fix for the first loop!). When the serializer goes to create the representation for the `SearchResult` object (that's what the `instance` is in the `to_representation` call in this case), it calls both SerializerMethodField code separately. There is no query_set prefetch logic happening for `CourseSerializer` (we do a handful of others in search.py), so for each Course we put through the serializer, we were doing a lookup for all of its course_runs in order... and each of those course_runs' seats.

By running `prefetch_related_objects` in the `to_representation` method before those `SerializerMethodField` fields are called, we're able to avoid an abundance of DB queries. See below the difference in query count with my local setup that returns 534 results.

Locally, `search/all/` before:

```
138 queries in 88.16ms
```

Locally, `search/all/` after:

```
39 queries in 29.10ms
```

New relic corroborates the existence of many, many Seat queries:

Screen Shot 2019-09-17 at 3 21 47 PM

### CODE REVIEW

**Review by mikix — APPROVED** [review]
Sure. Nice!

**Review by dianakhuang — APPROVED** [review]

**Comment by christopappas** [comment]
@mikix @dianakhuang Thanks for the quick review before! Re-requested review because I changed my approach. Dropped info in the description above, but, doing prefetching in the `to_representation` layer instead of in the SerailizerMethodFields themselves

**Review by mikix — APPROVED** [review]
That is not an approach I've seen elsewhere, but if it works, alright.

**Review by dianakhuang — APPROVED** [review]
Ditto to @mikix

**Pull request merged**
