### PR TITLE
Respect partner when updating organizations

### PR DESCRIPTION
**Pull request by rlucioni**
An organization key is only unique in combination with a partner.

LEARNER-583

### CODE REVIEW

**Review by clintonb — APPROVED** [review]
Add a test.

**Comment by rlucioni** [comment]
@clintonb @schenedx I've added a test. Either let me know when this is ready to go out, or one of you feel free to merge and deploy this.

**Comment by rlucioni** [comment]
Correction: I'll merge and deploy this to stage, but I'll hold off on the production deployment until I hear from one of you.

**Review by schenedx — APPROVED** [review]
👍

**Pull request merged**
