### PR TITLE
Django 3.2 upgrade: replace drf dynamic fields

### PR DESCRIPTION
**Pull request by giovannicimolin**
Related ticket at https://github.com/edx/upgrades/issues/49.

**Testing instructions:**
1. Make sure all CI checks are passing.
2. Checkout this branch on your devstack.
3. Run `make discovery-shell` and install requirements `make requirements`.
4. Log in the LMS, then go to the discovery courses API and test a few cases:
- Check the `omit` parameter works: http://localhost:18381/api/v1/courses/?omit=title
- Check the `fields` parameter works: http://localhost:18381/api/v1/courses/?fields=title

*Reviewers:*
- [ ] @awais786

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-6115](https://openedx.atlassian.net/browse/OSPR-6115) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by awais786** [comment]
Lots of tests failing.

**Comment by giovannicimolin** [comment]
@awais786 Yup, I'll check what's going on with the tests today.

**Comment by natabene** [comment]
@giovannicimolin Thank you for this contribution. Let us know when this is ready.

**Comment by giovannicimolin** [comment]
@awais786 One of the issues I've found is that the replacement library relies on DRF's request object, which is not generated when using `APIRequestFactory` (it returns Django's Http request object instead). 
I've fixed that and left an explanation in the comments and will work on any remaining broken tests once the next run finishes.

**Comment by giovannicimolin** [comment]
@natabene @awais786 I've rebased the PR, added test instructions to the description, and re-worded the commits to follow OEP-51 guidelines.
This is ready for review now.

**Comment by giovannicimolin** [comment]
@natabene How can I re-run tests with the new GitHub Actions?

**Comment by awais786** [comment]
You can click on details link of failed job and re-run.

Last option is close and reopen the PR.

**Comment by giovannicimolin** [comment]
All CI checks are green now. :heavy_check_mark:

**Comment by giovannicimolin** [comment]
@awais786 I think I'm getting a few flaky tests here. Can you re-run the workflows again? I don't have permission to do that.

**Comment by natabene** [comment]
@giovannicimolin Can you address the failing test once you have a moment?

**Comment by giovannicimolin** [comment]
@natabene Sure! That is a flaky test, so I'll push a new commit to rerun the whole test suite - and fix any outstanding issues early in my day tomorrow.
Can you check if there's a way to give us permissions to re-run the CI checks without needing to push code?

Previously, I'd just ask `jenkins`, but now there's no option to rerun checks in GitHub Actions.

**Comment by giovannicimolin** [comment]
@natabene Checks are green :)

**Review by attiyaIshaque — APPROVED** [review]
@giovannicimolin Changes looks good to me.
Also I have tested it according to your testing instructions. 👍 

please rebase your branch with the latest master changes.

**Comment by giovannicimolin** [comment]
@attiyaIshaque I've merged the master branch and tests are passing. :grin:

**Comment by natabene** [comment]
@attiyaIshaque Could we merge?

**Comment by attiyaIshaque** [comment]
@natabene Yes. I am merging.

**Comment by openedx-webhooks** [comment]
@giovannicimolin 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/course-discovery&entry.867055334=https://github.com/edx/course-discovery/pull/3174&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2021-10-06+20:57&entry.1917517419=2021-11-17+06:40&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
